# Generated by Django 3.2.5 on 2021-07-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('food', models.TextField()),
                ('food_price', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('post', models.CharField(blank=True, choices=[('waiter', 'Waiter'), ('cook', 'Cook'), ('administrator', 'Administrator')], max_length=25)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.city')),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.country')),
                ('menu', models.ManyToManyField(to='restaurants.Menu')),
                ('workers', models.ManyToManyField(to='restaurants.Workers')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Ресторани',
            },
        ),
    ]
